### ISSUE TITLE
display minizinc solution

### ISSUE THREAD

**Issue by rpapad01** [isa-group/governify-csp-tools#16]
Is there any way which let me print the solution that minizinc return?

**Comment by feserafim** [comment]
According to reasoner function, you could obtain the standard execution output from `stdout` parameter.

```javascript
// Solve CSP
reasoner.solve(cspModel, (err, stdout, stderr, isSatisfiable) => {
    if (err) {
        // manage error
    } else {
        // manage solution
    }
});
```

**Comment by fevisera** [comment]
I believe https://github.com/isa-group/governify-csp-tools/issues/16#issuecomment-368775009 answers this issue. Thus I'm closing this issue.

Thanks for asking @rpapad01.
